[tests] Define `jest`/`ts-jest` deps at the root level
And remove `jest`/`ts-jest` from the individual packages. It is
important to have a consistent version of `jest` being used throughout
the monorepo, otherwise bizarre errors surface that cause jest to crash,
such as:

```
TypeError: this._environment.runScript is not a function

  at Runtime._execModule (../../node_modules/jest-runner/node_modules/jest-runtime/build/index.js:856:41)
```