[cli] Throw explicit error when vercel.ts `routes` conversion creates a conflict (#14709)
https://github.com/vercel/vercel/pull/14705 fixes this use case of
vercel.ts:

```ts
// ✅ fixed
export const config: VercelConfig = {
  routes: [
    routes.rewrite('/test-header', 'https://httpbin.org/headers', {
      requestHeaders: {
        authorization: `Bearer token`,
      },
    }),
    routes.redirect('/test-build', 'https://httpbin.org/headers'),
  ]
};
```

But the user can still have a confusing experience if they do this:

```ts
// ❌ not fixed
export const config: VercelConfig = {
  rewrites: [
    routes.rewrite('/test-env', 'https://httpbin.org/headers', {
      requestHeaders: {
        authorization: `Bearer ${deploymentEnv('API_TOKEN')}`,
      },
    }),
    routes.rewrite('/test-rewrite-regular', 'https://httpbin.org/headers')
  ],
  redirects: [
    routes.redirect('/test-build', 'https://httpbin.org/headers'),
  ]
};
```

This will fail with the error message:

```
Error: If `rewrites`, `redirects`, `headers`, `cleanUrls` or `trailingSlash` are used, then `routes` cannot be present.
```

But that's not clear because from the user's perspective they separated
their rewrites and redirects like the docs say, so where is `routes`
coming from?

We're not going to compile the `redirects` to routes
(https://github.com/vercel/vercel/pull/14679), so we need the error
message to be clearer.

This PR fails the build during config compilation if after normalization
(AKA compiling anything to `routes` that needs this transformation)
there's still a conflict. In this case, since it has the full context of
what just happened (unlike the generic vercel.json error it currently
throws) it can throw a more descriptive error message with clear
instructions for what to do.

<img width="424" height="276" alt="Screenshot 2026-01-23 at 5 12 34 PM"
src="https://github.com/user-attachments/assets/c65de5c5-d625-418e-9152-4a597a95ea01"
/>