[tests] refactor exit code assertions (#12441)
The assertion `expect(somePromise).resolves.toEqual(someValue)` has two failure modes:

1. the resolved value doesn't match the given value
2. the promise is rejected

In the (1) case, the failure message is fine. However, the (2) case truncates the rejection message:

```
 FAIL  test/unit/commands/link/index.test.ts > link > should track use of deprecated `cwd` positional argument
AssertionError: promise rejected "'some long message about why this is b…'" instead of resolving
 ❯ test/unit/commands/link/index.test.ts:348:19
    346|     // const exitCode = await exitCodePromise;
    347|     const p = Promise.reject('some long message about why this is brok…
    348|     await expect(p).resolves.toEqual(1);
       |                   ^
    349| 
    350|     expect(client.telemetryEventStore).toHaveTelemetryEvents([
```

The reason is truncated like this:

> some long message about why this is b…

Which makes this assertion pretty useless compared to the basic replacement.

---

This PR replaces the general pattern:

```
const exitCodePromise = alias(client);
await expect(exitCodePromise).resolves.toEqual(0);
```

with:

```
const exitCode = await alias(client);
expect(exitCode, 'exit code of "alias"').toEqual(0);
```

---

Example of new error:

```
 FAIL  test/unit/commands/link/index.test.ts > link > should track use of deprecated `cwd` positional argument
Error: some long message about why this is broken that you cannot read
 ❯ test/unit/commands/link/index.test.ts:348:14
    346|     // const exitCode = await exitCodePromise;
    347|     const p = new Promise((resolve, reject) => {
    348|       reject(new Error('some long message about why this is broken tha…
       |              ^
    349|     })
    350|     const v = await p;
 ❯ test/unit/commands/link/index.test.ts:347:15
```

Which shows the reason:

> some long message about why this is broken that you cannot read