[examples] pin astro to specific node engine (#12793)
I don't _love_ this solution but: Astro adapter for `astro@4`
(maintained by the Astro team) isn't compatible with `node@22` which is
our current default for new deploys.

> 19:00:52 [build] Rearranging server assets...
> 19:00:52 [WARN] [@astrojs/vercel/serverless]
> The local Node.js version (22) is not supported by Vercel Serverless
Functions.
> 	Your project will use Node.js 18 as the runtime instead.
> 	Consider switching your local version to 18.

We attempt to fall back to `node@18`, which fails 

> Error: The following Serverless Functions contain an invalid
"runtime":
> - _render (nodejs18.x). Learn More:
https://vercel.com/guides/serverless-function-contains-invalid-runtime-error
> 

I suspect because we've set `node@22` somewhere before building.

We should update the astro example to `astro@5` anyway, but that might
involve a bit more work. Setting `engines` in the `package.json` at
least makes the example deployable again while we address the issue.

Manually setting to other supported node versions (even `node@18`) and
doing redeploy resolves the issue, but the current state just results in
failed attempts to deploy the templated.

Picked `node@20` since it's the highest supported version.