Mark SvelteKit as superseding vite
Currently, when trying to use sveltekit with
`VERCEL_USE_EXPERIMENTAL_SERVICES=1` in zero-config mode, we get
errors like:
```
Error: Multiple frameworks detected in frontend/: SvelteKit, Vite. Use explicit experimentalServices config.
```
from the services auto-detection.

SvelteKit depends on Vite, so it's expected for both to be present. In
this case the culprit is that SvelteKit isn't marked as superseding
Vite.

Tested manually but I didn't write a test because I couldn't find any
similar sort of testing.

There might be other lurking issues of this form, since it seems like
many call sites just take the first framework found.