[services] detect and handle venv management for multi-service project (#14952)
Adds detection of an activated virtual environment and its management
for Python services in a multi-service project. This is the first step
before adding automatic dependencies synchronization.

If a project has more than one Python service, the CLI will exit with a
clear message about how to fix the setup:
```
Error: Detected activated venv at /Users/nik/Projects/vercel/experiments/apps-services/services/service-a/.venv, vercel dev manages virtual environments automatically.
Run deactivate and try again.
```

This is necessary to prevent issues that arise when multiple Python
services (for example, FastAPI with `uvicorn` and Flask with `werkzeug`)
are used in the same project, which results into displaying obscure
errors about missing dependencies. If there's one 1 Python services,
then activated venv is allowed.