[remix] Add better error message when server build directory is missing
Show a more helpful message instead of showing a cryptic error messsage:

> Error: ENOENT: no such file or directory, copyfile '/var/task/node_modules/@vercel/remix/server-node.mjs' -> '/vercel/path0/packages/web/build/server-node.mjs'

This is probably due to a bad user configuration (i.e. with Turbo),
but tell them to contact support anyways in case there is a different
cause that we would need to address.