[now-python] Add `setup.cfg` file before running `pip install` (#292)
* [now-python] Add `setup.cfg` file before running `pip install`

See: https://stackoverflow.com/a/44728772/376773

The `setup.cfg` is required for `now dev` on MacOS, where without
this file being present in the src dir then this error happens:

distutils.errors.DistutilsOptionError: must supply either home
or prefix/exec-prefix -- not both

* Only create the `seup.cfg` file once