[go] fix go ci failing e2e tests (#14640)
Fixes CI e2e fixture builds failing with the following error by
upgrading the minimum go version in the fixtures from 1.13 -> 1.18 as
[aws-lambda-go](https://github.com/aws/aws-lambda-go/blob/main/go.mod)
relies on 1.18 and
[vercel/go-bridge](https://github.com/vercel/go-bridge/blob/master/go/bridge/bridge.go)
relies on aws-lambda-go
```
go: extracting gopkg.in/yaml.v3 v3.0.1
go: downloading gopkg.in/check.v1 v0.0.0-20161208181325-20d25e280405
go: extracting gopkg.in/check.v1 v0.0.0-20161208181325-20d25e280405
handler imports
	github.com/vercel/go-bridge/go/bridge imports
	github.com/aws/aws-lambda-go/lambda imports
	github.com/aws/aws-lambda-go/lambdacontext imports
	log/slog: malformed module path "log/slog": missing dot in first path element
failed to `go mod tidy`
Error: Command failed: go mod tidy
```