[cli] Move readme copy logic to a helper function for `vc link`
ncc has an issue with detecting + rewriting this file path for some
reason. Moving to a helper function should work around that issue.

Fixing:

```
Error: ENOENT: no such file or directory, open '/node_modules/vercel/projects/VERCEL_DIR_README.txt'
```