[go] improve error message on failed go build (#15651)
Currently, the error message on failed go build looks like:
```
Command failed: go build -ldflags -s -w -o /tmp/418328cb/user-server .
```
Which is not very helpful
Show stderr and/or stdout on failed go build

Now it shows, e.g.:
```
Command failed: go build -ldflags -s -w -o /tmp/1a0b9a5f/user-server .
# test-failure
./main.go:11:6: undefined: thisSymbolDoesNotExist
```