[python] Pass link-mode=copy when installing vercel-workers. (#16318)
Fixes issue with installing vercel-workers with a restored `venv` that
was cached from a previous build:

```
Error: Failed to run "uv pip install vercel-workers==0.0.22": Command failed: /usr/local/bin/uv pip install vercel-workers==0.0.22
Using Python 3.14.3 environment at: /vercel/path0/server/.vercel/python/services/worker/.venv
Resolved 16 packages in 34ms
Uninstalled 1 package in 0.95ms
error: Failed to install: vercel_workers-0.0.22-py3-none-any.whl (vercel-workers==0.0.22)
  Caused by: Failed to clone `/vercel/path0/server/.vercel/python/cache/uv/archive-v0/8BAwjdioJ3YaAIHYKU2gg/vercel_workers-0.0.22.dist-info/RECORD` to `/vercel/path0/server/.vercel/python/services/worker/.venv/lib/python3.14/site-packages/vercel_workers-0.0.22.dist-info/RECORD`
  Caused by: Invalid cross-device link (os error 18)
```

Signed-off-by: gscho <greg.c.schofield@gmail.com>