fix: support cancellation validation (#13831)
Right now deployments will fail because of a missing validation entry
with:

```
Error: Invalid vercel.json - should NOT have additional property `supportsCancellation`. Please remove it.
```

This PR fixes that.

---------

Co-authored-by: Craig Andrews <44933829+craigandrews@users.noreply.github.com>