fix(gitlab): support linking projects that belong to subgroups (#13295)
GitLab projects can belong to [subgroups up to 20
deep](https://docs.gitlab.com/user/group/subgroups/), our logic for
parsing repo paths would not allow for this.

Added unit tests

Manual test against own repository that belongs to a subgroup (failed
due to my personal account not being pro):

Before:
```
[1 olszewski@macbookpro] /Users/olszewski/code/vercel/vercel/packages/cli $ pnpm run vc --cwd /tmp/great-monorepo git connect https://gitlab.com/top-level8063919/middle-level/bottom-level/great-monorepo

> vercel@41.7.0 vc /Users/olszewski/code/vercel/vercel/packages/cli
> pnpm vercel "--cwd" "/tmp/great-monorepo" "git" "connect" "https://gitlab.com/top-level8063919/middle-level/bottom-level/great-monorepo"


> vercel@41.7.0 vercel /Users/olszewski/code/vercel/vercel/packages/cli
> ts-node ./src/index.ts "--cwd" "/tmp/great-monorepo" "git" "connect" "https://gitlab.com/top-level8063919/middle-level/bottom-level/great-monorepo"

Vercel CLI 41.7.0
Error: Failed to parse URL "https://gitlab.com/top-level8063919/middle-level/bottom-level/great-monorepo". Please ensure the URL is valid.
```
After:
```
[0 olszewski@macbookpro] /Users/olszewski/code/vercel/vercel/packages/cli $ pnpm run vc --cwd /tmp/great-monorepo git connect https://gitlab.com/top-level8063919/middle-level/bottom-level/great-monorepo

> vercel@41.7.0 vc /Users/olszewski/code/vercel/vercel/packages/cli
> pnpm vercel "--cwd" "/tmp/great-monorepo" "git" "connect" "https://gitlab.com/top-level8063919/middle-level/bottom-level/great-monorepo"


> vercel@41.7.0 vercel /Users/olszewski/code/vercel/vercel/packages/cli
> ts-node ./src/index.ts "--cwd" "/tmp/great-monorepo" "git" "connect" "https://gitlab.com/top-level8063919/middle-level/bottom-level/great-monorepo"

Vercel CLI 41.7.0
> Found a repository in your local Git Config: git@gitlab.com:top-level8063919/middle-level/bottom-level/great-monorepo.git
? Do you still want to connect https://gitlab.com/top-level8063919/middle-level/bottom-level/great-monorepo? yes
> Connecting Git remote: https://gitlab.com/top-level8063919/middle-level/bottom-level/great-monorepo
Error: Failed to connect the GitLab repository top-level8063919/middle-level/bottom-level/great-monorepo.
Error: The repository "top-level8063919/middle-level/bottom-level/great-monorepo" is owned by a group. Please link it to a Vercel Pro team instead. (409)
```