Fixes an error of missing context after logging in while deploying.
```
> Error! Unknown error: TypeError: Cannot read property 'username' of undefined
TypeError: Cannot read property 'username' of undefined
    at /usr/local/lib/node_modules/now/build/bin/now-deploy.js:316:115
    at Generator.next (<anonymous>)
    at c (/usr/local/lib/node_modules/now/build/bin/now-deploy.js:760:99)
```