Fix example api url (#14417)
https://now-example-files.zeit.sh/ has deployment protection so it
causes:

```
vc init
Vercel CLI 48.12.1
Error: Response Error (401)
```