[python tests] resolve python wheel urls in tests to fix broken CI (#15606)
CI is failing because Python builds in test dev are failing with:
```
Error: Failed to run "uv pip install vercel-runtime==0.9.0": Command failed: /usr/local/bin/uv pip install vercel-runtime==0.9.0
Using Python 3.12.12 environment at: .vercel/python/.venv
  × No solution found when resolving dependencies:
  ╰─▶ Because there is no version of vercel-runtime==0.9.0 and you require
      vercel-runtime==0.9.0, we can conclude that your requirements are
      unsatisfiable.
```

The latest published version of vercel-runtime on PyPI is 0.8.0

This PR wires in the same "Resolve Python wheel URLs" flow into
`test.yaml` that we have in `test-e2e.yml`