[python] relative paths in requirements.txt fix (#14022)
When we switched to installing dependencies to _vendor, we switched the
work path of the pip install step which made it so installing wheels
from relative paths would fail, e.g.:
```
fastapi==0.115.12
uvicorn[standard]==0.34.2
./wheels/example_pkg_one-1.0.0-py3-none-any.whl
./wheels/example_pkg_two-2.0.0-py3-none-any.whl
```

Would give this error:
```
Failed to run "/opt/homebrew/bin/uv pip install --no-compile --no-cache-dir --target _vendor --upgrade -r /Users/ricardo/Documents/code/vercel/packages/python/test/fixtures/37-reqs-rel-path/requirements.txt", falling back to pip
Failed to run "pip3.12 install --disable-pip-version-check --no-compile --no-cache-dir --target _vendor --upgrade -r /Users/ricardo/Documents/code/vercel/packages/python/test/fixtures/37-reqs-rel-path/requirements.txt"
Error: Command failed: pip3.12 install --disable-pip-version-check --no-compile --no-cache-dir --target _vendor --upgrade -r /Users/ricardo/Documents/code/vercel/packages/python/test/fixtures/37-reqs-rel-path/requirements.txt
WARNING: Requirement './wheels/example_pkg_one-1.0.0-py3-none-any.whl' looks like a filename, but the file does not exist
WARNING: Requirement './wheels/example_pkg_two-2.0.0-py3-none-any.whl' looks like a filename, but the file does not exist
ERROR: Could not install packages due to an OSError: [Errno 2] No such file or directory: '/Users/ricardo/Documents/code/vercel/packages/python/test/fixtures/37-reqs-rel-path/.vercel/python/py3.12/wheels/example_pkg_one-1.0.0-py3-none-any.whl'
```

This PR changes the work path of the install step so packages are still
installed to _vendor but relative install paths also work